version: '3.2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    container_name: elasticsearch-1
    environment:
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - type: bind
        source: ./elasticsearch/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic-network

  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.2
    container_name: kibana-1
    volumes:
      - type: bind
        source: ./kibana/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    ports:
      - "5601:5601"
    networks:
      - elastic-network
    depends_on:
      - elasticsearch

  logstash:
    image: docker.elastic.co/logstash/logstash:7.6.2
    container_name: logstash-1
    volumes:
      - type: bind
        source: ./logstash/logstash.yml
        target: /usr/share/logstash/config/logstash.yml
        read_only: true
      - type: bind
        source: ./logstash/io_filters
        target: /usr/share/logstash/pipeline
        read_only: true
      - /logs/HOSTS:/logs/HOSTS:rw
    ports:
      - "9600:9600/tcp"
    environment:
      - "LS_JAVA_OPTS=-Xmx1G -Xms1G"
    networks:
      - elastic-network
    depends_on:
      - elasticsearch

volumes:
  raw-data:
  es-data:
  elasticsearch:

networks:
  elastic-network:
    driver: bridge

